CREATE TABLE users
(
    id       int         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(10) NOT NULL

);

--- posts ----
CREATE TABLE posts
(
    id   int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(255)
);
CREATE TABLE comments
(
    id      int  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id int  NOT NULL,
    comment text NOT NULL

);
CREATE TABLE post_permissions
(
    id        int         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id   int         NOT NULL,
    user_id   int         NOT NULL,
    user_role varchar(20) NOT NULL
);
ALTER TABLE post_permissions
    ADD CONSTRAINT user_fk2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE post_permissions
    ADD CONSTRAINT post_fk2 FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;


CREATE OR REPLACE VIEW post_comment_permissions (id, v_post_id, v_comment_id, v_user_id, v_user_role) AS
SELECT c.id, p.id as v_post_id, c.id as v_comment_id, pp.user_id as v_user_id, pp.user_role as v_user_role
FROM comments c
         JOIN posts p ON c.post_id = p.id
         JOIN post_permissions pp ON pp.post_id = p.id;
