version: '3.6'
services:
  postgres1:
    image: postgres:12
    restart: always
    ports:
      - "35431:5432"
    environment:
      POSTGRES_USER: mydb
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: secret
    volumes:
      - ./all.sql:/docker-entrypoint-initdb.d/01-all.sql

    networks:
       - mynetwork

  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.11
    ports:
      - "8081:8080"
    links:
      - postgres1
    restart: always
    networks:
        - mynetwork
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://mydb:secret@postgres1:5432/mydb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, query-log
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ADMIN_SECRET: secret
##
networks:
  mynetwork:
    driver: "bridge"


volumes:
  db_data:

